# Checkov Configuration for Terraform Security Scanning
# Maintainer Notes:
# - To skip checks: add to `skip_check` list
# - To exclude files/folders: add to `skip_path`
# - CI filters HIGH/CRITICAL issues separately — do not add severity filtering here

skip_check:
  - CKV_GCP_30        # Example: GCS bucket should have uniform bucket-level access enabled

# skip_path:
#   - .github

# Optional: Allow suppressed check annotations to be marked in-line in .tf files
# suppress_comment: "checkov:skip=<check_id>:<reason>"
