name: Terraform Docs

runs-on: ubuntu-latest
steps:
  - name: Check out code
    uses: actions/checkout@v4
    with:
      ref: ${{ github.event.pull_request.head.ref }}

  - name: Render terraform docs and push back to PR
    uses: terraform-docs/gh-actions@main
    with:
      working-dir: .
      config-file: .terraform-docs.yml
  #    fail-on-diff: true
      output-file: README.md
      output-method: inject