name: Cleanup IAM Bindings
description: "This action cleans up stale IAM bindings for deleted service accounts in GCP. It checks the IAM bindings in terraform.tfvars and removes any bindings for service accounts that no longer exist."

inputs:
  project_id:
    description: "Project ID"
    required: true
  dry_run:
    description: "Enable dry run mode to simulate the cleanup without making changes"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:

    # Authenticate to GCP
    - name: Authenticate with GCP
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.service_account }}
        export_environment_variables: true
        
    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.project_id }}

    # Identify stale bindings 
    - name: Identify deleted service accounts
      id: identify
      shell: bash
      run: |
        echo "🔍 Identifying deleted service accounts in IAM bindings..."
        # Fetch IAM policy
        IAM_POLICY=$(gcloud projects get-iam-policy ${{ inputs.project_id }} --format=json)
        echo "✅ IAM policy fetched."

        # Extract deleted service accounts
        STALE_ACCOUNTS=$(echo "$IAM_POLICY" | jq -r '.bindings[] | select(.members[] | contains("deleted:serviceAccount")) | .members[] | select(startswith("deleted:serviceAccount")) | sub("deleted:serviceAccount:"; "") | sub("\\?.*"; "")' | sort -u)
        echo "🚨 Identified stale (deleted) service accounts: $STALE_ACCOUNTS"
        echo "stale_accounts<<EOF" >> $GITHUB_OUTPUT
        echo "$STALE_ACCOUNTS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    # Remove stale IAM bindings
    - name: Remove stale IAM bindings
      shell: bash
      run: |
        STALE_ACCOUNTS="${{ steps.identify.outputs.stale_accounts }}"
        if [ -z "$STALE_ACCOUNTS" ]; then
          echo "No stale service accounts found."
          exit 0
        fi

        echo "🧹 Removing IAM bindings for deleted service accounts..."
        for account in $STALE_ACCOUNTS; do
          echo "🔎 Processing $account"
          # Get roles associated with the deleted service account
          ROLES=$(gcloud projects get-iam-policy ${{ inputs.project_id }} --format=json | \
            jq -r --arg acct "$account" '.bindings[] | select(.members[] | contains("deleted:serviceAccount:\($acct)")) | .role')
          
          if [ -z "$ROLES" ]; then
            echo "No roles found for $account"
            continue
          fi

          for role in $ROLES; do
            echo "Processing role $role for $account"
            if [[ "${{ inputs.dry_run }}" == "true" ]]; then
              echo "Dry run enabled. Would remove binding: $account for role $role"
            else
              echo "Removing binding for $account with role $role"
              gcloud projects remove-iam-policy-binding ${{ inputs.project_id }} \
                --member="serviceAccount:$account" \
                --role="$role" || echo "Failed to remove $role for $account (may not exist)"
            fi
          done
        done

    # Verify IAM bindings
    - name: Verify IAM bindings
      shell: bash
      run: |
        echo "Verifying IAM bindings after cleanup..."
        gcloud projects get-iam-policy ${{ inputs.project_id }} --format=json