name: Cleanup IAM Bindings
description: "This action cleans up stale IAM bindings for deleted service accounts in GCP. It checks the IAM bindings in terraform.tfvars and removes any bindings for service accounts that no longer exist."

inputs:
  project_id:
    description: "Project ID"
    required: true
  dry_run:
    description: "Enable dry run mode to simulate the cleanup without making changes"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:

    - name: CHECK 
      run: echo "✅✅✅✅✅✅ now here..."
      shell: bash

    # Authenticate to GCP
    - name: Authenticate with GCP
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.service_account }}
        export_environment_variables: true
        
    - name: Set up Google Cloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.project_id }}

    # Identify stale bindings (Customize this step to match your stale logic)
    - name: Identify stale bindings
      shell: bash
      run: |
        echo "Identifying stale IAM bindings..."
        stale_bindings=$(cat bindings.json | jq '[.[] | select(.last_activity < "2023-01-01")]')
        echo "Identified stale bindings: $stale_bindings"
        echo "::set-output name=stale_bindings::$stale_bindings"

    # Remove stale IAM bindings (with dry run option)
    - name: Remove stale IAM bindings
      shell: bash
      run: |
        if [[ "${{ inputs.dry_run }}" == "true" ]]; then
          echo "Dry run enabled. Skipping removal of bindings."
          echo "The following bindings would have been removed: ${{ steps.identify.outputs.stale_bindings }}"
        else
          for binding in ${{ steps.identify.outputs.stale_bindings }}; do
            echo "Removing binding: $binding"
            gcloud projects remove-iam-policy-binding ${{ inputs.project_id }} \
              --member=$binding.member \
              --role=$binding.role
          done
        fi

    # Verify IAM bindings after cleanup
    - name: Verify IAM bindings
      shell: bash
      run: |
        echo "Verifying IAM bindings after cleanup..."
        gcloud iam policies list --project=${{ inputs.project_id }} --format=json