name: ZAP Security Scan
description: Run ZAP CLI against one endpoint

inputs:
  target:
    description: The URL to scan
    required: true

runs:
  using: "composite"
  steps:
    - name: Run ZAP CLI
      shell: bash
      run: |
        echo "Scanning ${{ inputs.target }} with ZAP..."
        docker run -v $(pwd):/zap/wrk/:rw \
          -t ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py -t "${{ inputs.target }}" -g gen.conf -r zap_report.html || true
