name: Terraform Deployment

# on: sji!
#     workflow_run:
#       workflows: ["Security Scan"] sonar?!
#       types:
#         - completed

on:
  push:
    branches:
      - dev
    #   - uat
    #   - prod
    # paths:
    #   - 'terraform/**'

jobs:
# iif: == 'success' sji! }}
  terraform-deploy:
    name: Terraform Validate
    runs-on: ubuntu-latest
    
    # Specify environment for prod branch
    environment: ${{ github.ref_name == 'prod' && 'prod' || '' }}

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_CREDENTIALS: ${{ secrets.TF_SA_KEY }}

    steps:

      # Authenticate to GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.TF_SA_KEY }}'  # Key from script

      - name: Terraform Lint
        uses: ./.github/actions/terraform/tf-lint

      - name: Terraform Build
        uses: ./.github/actions/terraform/tf-build


  render-terraform-docs:      
    name: Terraform Docs
    needs: terraform-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: Terraform Docs
        uses: ./.github/actions/terraform/tf-docs

