name: Security Scanning

# TODO

on:
  pull_request:
    paths:
      - '**.tf'
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Authenticate GitHub CLI
      #   run: |
      #     echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: SAST Scan
        uses: ./.github/actions/security/sast
