name: Security Pentest Scanning

on:
  workflow_dispatch:

jobs:
  extract-endpoints:
    runs-on: ubuntu-latest
    outputs:
      endpoints_json: ${{ steps.extract_endpoints.outputs.endpoints_json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Endpoints
        id: extract_endpoints
        uses: ./.github/actions/terraform/endpoints
        with:
          service_account: ${{ secrets.SA_KEY }}
          project_id: coral-370212
          terraform_version: 1.6.6

  zap-scan:
    needs: extract-endpoints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        endpoint: ${{ fromJson(needs.extract-endpoints.outputs.endpoints_json) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ZAP CLI Scan
        uses: ./.github/actions/security/zap
        with:
          target: ${{ matrix.endpoint }}
