# requires /scripts/setup_tf/create_bootstrap_sa.sh to be run manually first
# this will bootstrap a terraform service account with permissions to create the bucket 
# and obv the project itself must be created - LZ required sji
name: Setup Terraform State Bucket

on:
  workflow_dispatch:  # Manual trigger for initial setup

jobs:
  setup-service-account:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.BOOTSTRAP_SA_NAME }}  # Bootstrap SA for creating new SA
          export_default_credentials: true

      # Run sa creation script
      - name: Create Terraform State Service Account
        run: |
          chmod +x scripts/setup_tf/create_tf_state_service_account.sh
          scripts/setup_tf/create_tf_state_service_account.sh
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          BUCKET_NAME: "${{ secrets.PROJECT_PREFIX }}-${{ secrets.TF_BUCKET_NAME }}" # -ENVIRONMENT  #SJI ALSO ADD REGION POSTFIX? crl-state-store-uat-eu-west-2?
          # ADMIN_EMAIL: ADMIN_EMAIL  #SJI SHOULD WE?
          # DEVELOPER_EMAIL: DEVELOPER_EMAIL #SJI SHOULD WE?
          
      # Store service account key in secrets
      - name: Add Secret - TF Service Account Key 
        run: |
          chmod +x scripts/setup_tf/create_github_secret.sh
          scripts/setup_tf/create_github_secret.sh
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          BUCKET_NAME: "${{ secrets.PROJECT_PREFIX }}-${{ secrets.TF_BUCKET_NAME }}" # -ENVIRONMENT  #SJI ALSO ADD REGION POSTFIX? crl-state-store-uat-eu-west-2?
          # ADMIN_EMAIL: ADMIN_EMAIL  #SJI SHOULD WE?
          # DEVELOPER_EMAIL: DEVELOPER_EMAIL #SJI SHOULD WE?
          #?token here??
          
      # # Store service account key in secrets (optional, requires manual handling)
      # - name: Store Service Account Key - Manual Step !IMPORTANT!
      #   run: |
      #     echo "IMPORTANT! Service account key generated at sa-tf-state-key.json"
      #     echo "Please manually store this key in GitHub Secrets as GCP_TF_STATE_SA_KEY"          

  setup-bucket:
    needs: setup-service-account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.TF_SA_KEY }}  # Key from script
          export_default_credentials: true

      - name: Create Terraform State Bucket
        run: |
          chmod +x scripts/setup_tf/create_tf_state_bucket.sh
          scripts/setup_tf/create_tf_state_bucket.sh
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          BUCKET_NAME: "${{ secrets.GCP_PROJECT_ID }}-tf-state"
          # ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          # DEVELOPER_EMAIL: ${{ secrets.DEVELOPER_EMAIL }}