name: Setup Terraform
# requires /scripts/setup_tf/create_bootstrap_sa.sh to be run manually first
# this will bootstrap a terraform service account with permissions to create the bucket 
# and obv the GCP project itself must be created - LZ required sji

on:
  workflow_dispatch:  # Manual trigger for initial setup
#todo! backup state bucket somewhere using bootstrap account and schedule  it sji 
jobs:
  setup-service-account:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Install gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.TF_BOOTSTRAP_SA }}  # Bootstrap SA
          export_default_credentials: true #important for gcloud commands to work

      # Run sa creation script
      - name: Create Terraform State Service Account
        run: |
          chmod +x scripts/setup_tf/create_tf_state_service_account.sh
          scripts/setup_tf/create_tf_state_service_account.sh ${{ env.PROJECT_ID }} 
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          BUCKET_NAME: "${{ env.BUCKET_NAME }}" # -ENVIRONMENT  #SJI ALSO ADD REGION POSTFIX? crl-state-store-uat-eu-west-2?
          # ADMIN_EMAIL: ADMIN_EMAIL  #SJI SHOULD WE?
          # DEVELOPER_EMAIL: DEVELOPER_EMAIL #SJI SHOULD WE?
          
      # # Store service account key in secrets
      # - name: Add Secret - TF Service Account Key 
      #   run: |
      #     chmod +x scripts/setup_tf/add_github_secret.sh
      #     scripts/setup_tf/add_github_secret.sh 
      #   env:
      #     PROJECT_ID: {{ env.PROJECT_ID }}
      #     BUCKET_NAME: "{{ env.BUCKET_NAME }}"  # -ENVIRONMENT  #SJI ALSO ADD REGION POSTFIX? crl-state-store-uat-eu-west-2?
          # ADMIN_EMAIL: ADMIN_EMAIL  #SJI SHOULD WE?
          # DEVELOPER_EMAIL: DEVELOPER_EMAIL #SJI SHOULD WE?
          #?token here??      

  setup-bucket:
    needs: setup-service-account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.TF_SA_KEY }}  # Key from script
          export_default_credentials: true

      - name: Create Terraform State Bucket
        run: |
          chmod +x scripts/setup_tf/create_tf_state_bucket.sh
          scripts/setup_tf/create_tf_state_bucket.sh
        env:
          PROJECT_ID: ${{ env.PROJECT_ID }}
          BUCKET_NAME: "${{ env.BUCKET_NAME }}"
          # ADMIN_EMAIL:  secrets.ADMIN_EMAIL }}
          # DEVELOPER_EMAIL: secrets.DEVELOPER_EMAIL }}